apiVersion: v1
kind: Service
metadata:
  name: {{ include "messages.fullname" . }}
  labels:
    {{- include "messages.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "least_connections"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-type: "cookies"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-name: "messages"
    service.beta.kubernetes.io/do-loadbalancer-sticky-sessions-cookie-ttl: "3600"
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4050
      protocol: TCP
      name: http
  selector:
    {{- include "messages.selectorLabels" . | nindent 4 }}
